import { Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import MenuSuperior from "../components/MenuSuperior";
import styles from "../styles/Home.module.css";
import { estadoHora } from "../zustand/horaPolla";

export default function Home() {
  const { hora, horaCatar, horaColombia, pais } = estadoHora();
  const handleButtonCatar = () => {
    horaCatar();
  };
  const handleButtonColombia = () => {
    horaColombia();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Catar 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <MenuSuperior /> */}
        <h4>NP 2022</h4>
        <h5>{pais}</h5>
        {hora > 0 ? (
          <Button variant="contained" onClick={handleButtonCatar}>
            Catar {hora}
          </Button>
        ) : (
          <Button variant="contained" onClick={handleButtonColombia}>
            Colombia {hora}
          </Button>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

/* 
Integración Material UI Next.js
https://dev.to/hajhosein/nextjs-mui-v5-tutorial-2k35
*/
