import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../../styles/Home.module.css";
import MenuSuperior from "../MenuSuperior";

export const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Solo Catar 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuSuperior />
      {children}
      <footer className={styles.footer}>
        Nuestra POLLA 2022
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </>
  );
};

/*



*/
